{% set name = "dask-databricks" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dask_databricks-{{ version }}.tar.gz
  sha256: 09dc89dbb472270ab5491891f65199a4a258d9e6214e7bfb8243077aa71515bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - bokeh <=3.2.2
    - click >=8.1
    - dask-core
    - rich
    - distributed

test:
  imports:
    - dask_databricks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jacobtomlinson/dask-databricks
  summary: Cluster tools for running Dask on Databricks
  dev_url: https://github.com/dask-contrib/dask-databricks
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
    - skirui-source
